### ISSUE TITLE
Optical Illusion modifier only working for host

### ISSUE THREAD

**Issue by leonissenbaum** [TheMysticSword/ChallengeMode#3]
Playing multiplayer, the optical illusion (all chests are cloaked) modifier is only working for the host, and other players see chests normally. Other modifiers, which are "Broken Spine" and "What Could This Be?", are working properly, though they're not displayed for the other players.

**Comment by leonissenbaum** [comment]
As an update, modifiers are displayed for other players starting on stage 2.

**Comment by TheMysticSword** [comment]
Modifiers should now be properly networked on stage 1. Feel free to request a re-open of this in case it still happens
